# Generated by Django 5.1 on 2024-10-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
