# Generated by Django 5.1 on 2024-10-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0002_alter_adminlog_email_alter_adminlog_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
