# Generated by Django 5.1 on 2024-10-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0003_alter_adminlog_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='surname',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
