# Generated by Django 5.1 on 2024-10-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0004_adminlog_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='testJava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('Option1', models.CharField(max_length=250)),
                ('Option2', models.CharField(max_length=250)),
                ('Option3', models.CharField(max_length=250)),
                ('Option4', models.CharField(max_length=250)),
                ('CorrectOption', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='testPython',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('Option1', models.CharField(max_length=250)),
                ('Option2', models.CharField(max_length=250)),
                ('Option3', models.CharField(max_length=250)),
                ('Option4', models.CharField(max_length=250)),
                ('CorrectOption', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='testScratch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('Option1', models.CharField(max_length=250)),
                ('Option2', models.CharField(max_length=250)),
                ('Option3', models.CharField(max_length=250)),
                ('Option4', models.CharField(max_length=250)),
                ('CorrectOption', models.CharField(max_length=250)),
            ],
        ),
    ]
