# Generated by Django 5.1 on 2024-10-10 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0005_testjava_testpython_testscratch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testjava',
            old_name='question',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='testpython',
            old_name='question',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='testscratch',
            old_name='question',
            new_name='Question',
        ),
    ]
