# Generated by Django 5.1 on 2024-10-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0010_alter_testjava_correctoption_alter_testjava_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjava',
            name='Option1',
            field=models.CharField(default='Default Option 1', max_length=250),
        ),
        migrations.AlterField(
            model_name='testjava',
            name='Option2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testjava',
            name='Option3',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testjava',
            name='Option4',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testjava',
            name='Question',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testpython',
            name='Option1',
            field=models.CharField(default='Default Option 1', max_length=250),
        ),
        migrations.AlterField(
            model_name='testpython',
            name='Option2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testpython',
            name='Option3',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testpython',
            name='Option4',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testpython',
            name='Question',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testscratch',
            name='Option1',
            field=models.CharField(default='Default Option 1', max_length=250),
        ),
        migrations.AlterField(
            model_name='testscratch',
            name='Option2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testscratch',
            name='Option3',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testscratch',
            name='Option4',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testscratch',
            name='Question',
            field=models.CharField(max_length=250),
        ),
    ]
