# Generated by Django 5.1 on 2024-10-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0011_alter_testjava_option1_alter_testjava_option2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testJava',
        ),
        migrations.DeleteModel(
            name='testPython',
        ),
        migrations.DeleteModel(
            name='testScratch',
        ),
    ]
