# Generated by Django 5.1 on 2024-10-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0012_delete_testjava_delete_testpython_delete_testscratch'),
    ]

    operations = [
        migrations.CreateModel(
            name='testJava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=250)),
                ('Option1', models.CharField(max_length=250)),
                ('Option2', models.CharField(max_length=250)),
                ('Option3', models.CharField(max_length=250)),
                ('Option4', models.CharField(max_length=250)),
                ('CorrectOption', models.CharField(max_length=250)),
            ],
        ),
    ]
