# Generated by Django 5.1 on 2024-10-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0013_testjava'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjava',
            name='Question',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
