# Generated by Django 5.1 on 2024-10-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0016_javascore_pythonscore_scratchscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pythonscore',
            old_name='user',
            new_name='scoreUser',
        ),
    ]
