# Generated by Django 5.1 on 2024-10-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0017_rename_user_pythonscore_scoreuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pythonscore',
            old_name='scoreUser',
            new_name='user',
        ),
    ]
