# Generated by Django 5.1 on 2024-10-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0018_rename_scoreuser_pythonscore_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='announc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contect', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
