# Generated by Django 5.1 on 2024-10-27 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0020_javavideo_pythonvideo_scratchvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminLog',
        ),
        migrations.AlterField(
            model_name='javavideo',
            name='video_file',
            field=models.FileField(upload_to='java_videos/%y'),
        ),
        migrations.AlterField(
            model_name='pythonvideo',
            name='video_file',
            field=models.FileField(upload_to='python_videos/%y'),
        ),
        migrations.AlterField(
            model_name='scratchvideo',
            name='video_file',
            field=models.FileField(upload_to='scratch_videos/%y'),
        ),
        migrations.AlterField(
            model_name='javascore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edu_sw.user'),
        ),
        migrations.AlterField(
            model_name='pythonscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edu_sw.user'),
        ),
        migrations.AlterField(
            model_name='scratchscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edu_sw.user'),
        ),
    ]
