# Generated by Django 5.1 on 2024-11-04 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0022_choice_alter_javascore_user_alter_pythonscore_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='SQL_videos/%y')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='choice',
            new_name='Occupation',
        ),
        migrations.RenameModel(
            old_name='ScratchScore',
            new_name='SQLScore',
        ),
        migrations.RenameModel(
            old_name='testScratch',
            new_name='testSQL',
        ),
        migrations.DeleteModel(
            name='ScratchVideo',
        ),
    ]
