# Generated by Django 5.1 on 2024-11-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_sw', '0023_sqlvideo_rename_choice_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javavideo',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pythonvideo',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sqlvideo',
            name='title',
            field=models.TextField(),
        ),
    ]
